### ISSUE TITLE
feature: Add Label Configuration for ollama Service in values.yaml

### ISSUE THREAD

**Issue by stepanbaghdasaryan** [open-webui/helm-charts#10]
**Description:**  
Currently, there is no option to configure labels for the `ollama` service in the `values.yaml` file. This feature is important for customizing specific configurations for the service and managing them effectively. This issue aims to add this functionality by making labels for the `ollama` service configurable in the `values.yaml` file.

**Expected Behavior:**  
It should be possible to configure labels for the `ollama` service in the `values.yaml` file to allow flexible customization of the configuration.

Add the following configuration in values.yaml:

```yaml
ollama:
  service:
    labels:
      my.custom.label: example-label
```

Use the `helm template` command to ensure that the configuration has been applied correctly. [yq](https://mikefarah.gitbook.io/yq/v/v3.x#install) Package is necessary for the following command:

```bash
helm template \
    open-webui \
    . \
    -n open-webui \
    -f values.yaml \
  |yq 'select(.kind=="Service")' | yq 'select(.metadata.name=="ollama")'
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    my.custom.label: example-label
    ...
...
```

**Additional Information:**  
- A fork of the repository has been created to implement this functionality. A [pull request](https://github.com/open-webui/helm-charts/pull/9) will be made upon completion of this issue.
