### ISSUE TITLE
bug:  Issue with Hosting WebUI Using Default Ingress Template - "Backend Service Does Not Exist" Error

### ISSUE THREAD

**Issue by abhishek-ch** [open-webui/helm-charts#12]
I'm encountering an issue when attempting to host the WebUI with a remote URL using the current default template. I consistently receive an error stating, "Backend service does not exist."

It seems there might be a problem with the way the ingress is set up in the default template. 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  labels:
    helm.sh/chart: open-webui-1.0.0
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"*********","
authorizationEndpoint":"*********","tokenEndpoint":"******",
"userInfoEndpoint":"https://graph.microsoft.com/oidc/userinfo",
"secretName":"some-secret"}'
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/group.name: default
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80 },{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - host: rwechat.ieg.int.bayer.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              name: http
```

The rerouting port is different from the actual containerport ie 80:8080. This maybe the reason, but I am not sure
