### ISSUE TITLE
Add Redis to helm chart

### ISSUE THREAD

**Issue by tkg61** [open-webui/helm-charts#135]
With the support of redis and websockets, having this available in the helm chat would be great!

**Comment by jyje** [comment]
I think three options would work well:

- add the redis subchart and link it
- link to the host of external redis
- do both

which option seems best?

**Comment by tkg61** [comment]
I would say both would be fantastic. Larger installs will want to possibly use one they already have or want to keep separate and smaller or dedicated installs will want an easy button :)

**Comment by jyje** [comment]
I missed smaller one. How about 3 scenario? based on [this doc](https://docs.openwebui.com/getting-started/advanced-topics/env-configuration#redis), I'm writing the first draft for pilot.

| **Install Scenario** | **Description**                                                                 | **redis.enabled** | **redisCluster.enabled** |
|---------------------|---------------------------------------------------------------------------------|--------------------------------------|--------------------------------------------|
| Small       | Default installation: 1 Redis server using k8s Deployment               | `true`                               | `false`                                    |
| Full        | High availability: Redis cluster using Bitnami Helm chart                      | `false`                              | `true`                                     |
| External      | Use an external Redis instance instead of deploying one in the chart         | `false`                              | `false`                                    |


these are proposed parts of `values.yaml`

```
websocket:
  # -- Enables websocket support in Open WebUI with env `ENABLE_WEBSOCKET_SUPPORT`
  enabled: false
  # -- Specifies the websocket manager to use with env `WEBSOCKET_MANAGER`: redis (default)
  manager: redis
  # -- Specifies the URL of the Redis instance for websocket communication
  url: redis://websocket-redis:6379/0
  # -- Deploys a redis
  redis:
    # -- Enable redis installation
    enabled: true
    # -- Redis name
    name: websocket-redis
    # -- Redis labels
    labels: {}
    # -- Redis annotations
    annotations: {}
    # -- Redis image
    image:
      repository: redis
      tag: 7.4.2-alpine3.21
      pullPolicy: IfNotPresent
    # -- Redis service
    service:
      # -- Redis container/target port
      containerPort: 6379
      # -- Redis service type
      type: ClusterIP
      # -- Redis service labels
      labels: {}
      # -- Redis service annotations
      annotations: {}
      # -- Redis service port
      port: 6379
      # -- Redis service node port
      nodePort: ""
  # -- Deploys a redis cluster with subchart (bitnami chart)
  redisCluster:
    # -- Enable redis installation
    enabled: false
    # ...
    # ...
    # ...
```

I'm testing small scenario now. If you can say this draft looks good, we can start based on it. Please give me any advice.
