### ISSUE TITLE
Helmfile issue when using transformer on open-webui chart

### ISSUE THREAD

**Issue by scodeman** [open-webui/helm-charts#147]
See: https://github.com/helmfile/helmfile/issues/1893

**Bug description**
I am using the following helmfile.yaml to release openwebui and I wanted to add securityContext missing in the pipeline dependency deployment with a transformer
```
---
repositories:
- name: openwebui
  url: https://helm.openwebui.com
releases:
- name: openwebui
  chart: openwebui/open-webui
  version: 5.4.0
  transformers: 
   - apiVersion: builtin
     kind: ValueAddTransformer
     metadata:
       name: add-security-context-runAsNonRoot
     targets:
       - fieldPath: spec/template/spec/securityContext/runAsNonRoot
         selector:
           kind: Deployment
           name: open-webui-pipelines
     value: true
```

Running `helmfile template -f helmfile.yaml --debug` it ends up producing the following error which I can't relate with the chart
```
  line 8: cannot unmarshal !!map into string
  line 15: cannot unmarshal !!map into string
```
