### ISSUE TITLE
LDAP settings via ConfigMap

### ISSUE THREAD

**Issue by govindkailas** [open-webui/helm-charts#149]
Can `LDAP` settings be configured using a `ConfigMap`? This would be a valuable addition for internal testing.

**Comment by 0xThresh** [comment]
Hey @govindkailas, I believe it would be possible to configure LDAP through a ConfigMap. Take a look at the LDAP environment variables here: https://docs.openwebui.com/getting-started/advanced-topics/env-configuration/#ldap 

Note that the `PersistentConfig` env vars in Open WebUI can set values on the first startup, but writes those configurations to the backend database, meaning that further updates to those environment variables on the same deployment will have no effect.

**Comment by govindkailas** [comment]
@0xThresh - Thanks, the mentioned link is broken, but I guess you are referring to this, https://docs.openwebui.com/getting-started/env-configuration/#ldap 

How do I hook up the `ConfigMap` to the helm chart so that the OllamaWebUI deployments take it? Where is the helm template for the deployment coming from?

**Comment by govindkailas** [comment]
I figured it should go under `extraEnvVars` in values.yaml. I created a secret for the `DN` and `password` and pushed the remaining to the `ConfigMap`. 

```
# -- Env vars added to the Open WebUI deployment. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration/
extraEnvVars:
  # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
  - name: OPENAI_API_KEY
    value: "0p3n-w3bu!"
  - name: LDAP_APP_DN 
    valueFrom:
      secretKeyRef:
        name: ldap-secret
        key: LDAP_APP_DN
  - name: LDAP_APP_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ldap-secret
        key: LDAP_APP_PASSWORD        
  - name: ENABLE_LDAP
    valueFrom:
      configMapKeyRef:
        name: ldap-config
        key: ENABLE_LDAP   
  - name: LDAP_ATTRIBUTE_FOR_USERNAME
    valueFrom:
      configMapKeyRef:
        name: ldap-config
        key: LDAP_ATTRIBUTE_FOR_USERNAME
  - name: LDAP_SEARCH_BASE
    valueFrom:
      configMapKeyRef:
        name: ldap-config
        key: LDAP_SEARCH_BASE
  - name: LDAP_SERVER_HOST
    valueFrom:
      configMapKeyRef:
        name: ldap-config
        key: LDAP_SERVER_HOST
  - name: LDAP_SERVER_PORT
    valueFrom:
      configMapKeyRef:
        name: ldap-config
        key: LDAP_SERVER_PORT
  - name: LDAP_USE_TLS
    valueFrom:
      configMapKeyRef:
        name: ldap-config
        key: LDAP_USE_TLS  
```

Hopefully, this will be helpful to someone down the road!
