### ISSUE TITLE
Document how to use S3

### ISSUE THREAD

**Issue by hongbo-miao** [open-webui/helm-charts#151]
Thanks for https://github.com/open-webui/open-webui/issues/5763!

Currently I cannot find any info in https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml

It would be great to document how to use S3, thanks!

**Comment by 0xThresh** [comment]
Hi @hongbo-miao, thanks for submitting this. It looks like the relevant settings are:
- Set the `STORAGE_PROVIDER` env var to `s3`: https://docs.openwebui.com/getting-started/env-configuration#amazon-s3-storage
- Set the following S3 environment variables: https://docs.openwebui.com/getting-started/env-configuration#amazon-s3-storage 

The easiest way to start would probably be to use the `extraEnvVars` values to configure these. If you wanted to open a PR with an example after you've tested the setup, you could leave commented out values under `extraEnvVars` in `values.yaml`. 

Alternatively we could take this further and add to the Helm templates to support S3, with possible values looking something like the below:
```
storageProvider:
  provider: local | s3 | gcs 
  envVars:
    gcs_bucket_name: <name>  # if using GCS
    s3_access_key: <key ID> # if using AWS
    ...other S3 values
```

PRs or other ideas are welcome here, as I've never tested the S3 configuration and don't know how widely used it is. Thanks!
