### ISSUE TITLE
Change pipelines update strategy?

### ISSUE THREAD

**Issue by morotsgurka** [open-webui/helm-charts#179]
Is it possible to change the update strategy for Pipelines?

I'm currently using the open-webui chart with the pipelines sub-chart enabled with persistent storage using Longhorn. The problem is that on an upgrade i get multi-attach error since the old pod does not terminate before the new one is scheduled.

For other deployments i use:
```yaml
spec:
  replicas: 1
  strategy:
    type: Recreate
```
or
```yaml
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
```
