### ISSUE TITLE
Pod stuck during initialization

### ISSUE THREAD

**Issue by kaliavarun** [open-webui/helm-charts#205]
Hello,

It seems the webui pod is stuck during intitialization, although the status is Running.
```

Loading WEBUI_SECRET_KEY from file, not provided as an environment variable.
Generating WEBUI_SECRET_KEY
Loading WEBUI_SECRET_KEY from .webui_secret_key
/app/backend/open_webui
/app/backend
/app
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [open_webui.env] 'DEFAULT_LOCALE' loaded from the latest database entry
INFO  [open_webui.env] 'DEFAULT_PROMPT_SUGGESTIONS' loaded from the latest database entry
WARNI [open_webui.env]

WARNING: CORS_ALLOW_ORIGIN IS SET TO '*' - NOT RECOMMENDED FOR PRODUCTION DEPLOYMENTS.

INFO  [open_webui.env] Embedding model set: sentence-transformers/all-MiniLM-L6-v2
```

There are no logs past this. The pod crashes after sometime and restarts.

Also, there are no listening ports.
```

root@open-webui-0:/app/backend# cat /proc/net/tcp
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
root@open-webui-0:/app/backend#
```

Here is my values.yml

```
nameOverride: ""
namespaceOverride: "ollama"

ollama:
  # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
  enabled: false
  # -- If enabling embedded Ollama, update fullnameOverride to your desired Ollama name value, or else it will use the default ollama.name value from the Ollama chart
  fullnameOverride: "open-webui-ollama"
  # -- Example Ollama configuration with nvidia GPU enabled, automatically downloading a model, and deploying a PVC for model persistence
  # ollama:
  #   gpu:1
  #     number: 1
  #   models:
  #     pull:
  #       - llama3
  #     run:
  #       - llama3
  # runtimeClassName: nvidia
  # persistentVolume:
  #   enabled: true
  #   volumeName: "example-pre-existing-pv-created-by-smb-csi"

pipelines:
  # -- Automatically install Pipelines chart to extend Open WebUI functionality using Pipelines: https://github.com/open-webui/pipelines
  enabled: false
  # -- This section can be used to pass required environment variables to your pipelines (e.g. Langfuse hostname)
  extraEnvVars: []

tika:
  # -- Automatically install Apache Tika to extend Open WebUI
  enabled: false

# -- A list of Ollama API endpoints. These can be added in lieu of automatically installing the Ollama Helm chart, or in addition to it.
ollamaUrls: []

# -- Disables taking Ollama Urls from `ollamaUrls`  list
ollamaUrlsFromExtraEnv: false

websocket:
  # -- Enables websocket support in Open WebUI with env `ENABLE_WEBSOCKET_SUPPORT`
  enabled: false
  # -- Specifies the websocket manager to use with env `WEBSOCKET_MANAGER`: redis (default)
  manager: redis
  # -- Specifies the URL of the Redis instance for websocket communication. Template with `redis://[:<password>@]<hostname>:<port>/<db>`
  url: redis://open-webui-redis:6379/0
  # -- Deploys a redis
  redis:
    # -- Enable redis installation
    enabled: true
    # -- Redis name
    name: open-webui-redis
    # -- Redis labels
    labels: {}
    # -- Redis annotations
    annotations: {}
    # -- Redis pod
    pods:
      # -- Redis pod annotations
      annotations: {}
    # -- Redis image
    image:
      repository: redis
      tag: 7.4.2-alpine3.21
      pullPolicy: IfNotPresent
    # -- Redis command (overrides default)
    command: []
    # -- Redis arguments (overrides default)
    args: []
    # -- Redis resources
    resources: {}
    # -- Redis service
    service:
      # -- Redis container/target port
      containerPort: 6379
      # -- Redis service type
      type: ClusterIP
      # -- Redis service labels
      labels: {}
      # -- Redis service annotations
      annotations: {}
      # -- Redis service port
      port: 6379
      # -- Redis service node port. Valid only when type is `NodePort`
      nodePort: ""
    # -- Redis tolerations for pod assignment
    tolerations: []

    # -- Redis affinity for pod assignment
    affinity: {}

# -- Deploys a Redis cluster with subchart 'redis' from bitnami
redis-cluster:
  # -- Enable Redis installation
  enabled: false
  # -- Redis cluster name (recommended to be 'open-webui-redis')
  # - In this case, redis url will be 'redis://open-webui-redis-master:6379/0' or 'redis://[:<password>@]open-webui-redis-master:6379/0'
  fullnameOverride: open-webui-redis
  # -- Redis Authentication
  auth:
    # -- Enable Redis authentication (disabled by default). For your security, we strongly suggest that you switch to 'auth.enabled=true'
    enabled: false
  # -- Replica configuration for the Redis cluster
  replica:
    # -- Number of Redis replica instances
    replicaCount: 3

rag:
  # -- Enable RAG
  # ref: https://docs.openwebui.com/getting-started/env-configuration#retrieval-augmented-generation-rag
  enabled: false
  # -- Vector database configuration
  # ref: https://docs.openwebui.com/getting-started/env-configuration#vector_db
  vectorDB: ""
  # -- Embedding engine to use for RAG with env `RAG_EMBEDDING_ENGINE`: ""(empty), "ollama", "openai"
  # ref: https://docs.openwebui.com/getting-started/env-configuration#rag_embedding_engine
  embeddingEngine: ""
  # -- Embedding model to use for RAG with env `RAG_EMBEDDING_MODEL`
  # ref: https://docs.openwebui.com/getting-started/env-configuration#rag_embedding_model
  embeddingModel: ""

milvus:
  # -- Enable Milvus installation. Deploys a Milvus cluster/standalone with subchart 'milvus' from zilliztech
  # ref: https://github.com/zilliztech/milvus-helm/tree/master/charts/milvus
  enabled: false
  # -- Milvus fullname override (recommended to be 'open-webui-milvus')
  # - In this case, the Milvus uri will be 'http://[username:password@]open-webui-milvus:19530'
  fullnameOverride: open-webui-milvus
  # -- Active Milvus URI for RAG with env `MILVUS_URI`. If there is credentials in the uri, it will be used to connect to the Milvus server.
  # ref: https://docs.openwebui.com/getting-started/env-configuration#milvus_uri
  uri: "http://open-webui-milvus:19530"
  # -- Example `milvus.uri` with credentials (Not recommended for production. Use `env` with `secretKeyRef` instead)
  # uri: "http://username:password@open-webui-milvus:19530"
  # -- Active Milvus database for RAG with env `MILVUS_DB`
  # ref: https://docs.openwebui.com/getting-started/env-configuration#milvus_db
  db: default
  # -- Active Milvus token for RAG with env `MILVUS_TOKEN`
  # ref: https://docs.openwebui.com/getting-started/env-configuration#milvus_token
  token: {}

# -- Value of cluster domain
clusterDomain: cluster.local

annotations: {}
podAnnotations: {}
podLabels: {}
replicaCount: 1
# -- Strategy for updating the workload manager: deployment or statefulset
strategy: {}
# -- Open WebUI image tags can be found here: https://github.com/open-webui/open-webui
image:
  repository: ghcr.io/open-webui/open-webui
  tag: ""
  pullPolicy: "IfNotPresent"

serviceAccount:
  enable: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

# -- Configure imagePullSecrets to use private registry
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry>
imagePullSecrets: []
# imagePullSecrets:
# - name: myRegistryKeySecretName

# -- Probe for liveness of the Open WebUI container
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes>
livenessProbe: {}
# livenessProbe:
#   httpGet:
#     path: /health
#     port: http
#   failureThreshold: 1
#   periodSeconds: 10

# -- Probe for readiness of the Open WebUI container
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes>
readinessProbe: {}
# readinessProbe:
#   httpGet:
#     path: /health/db
#     port: http
#   failureThreshold: 1
#   periodSeconds: 10

# -- Probe for startup of the Open WebUI container
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes>
startupProbe: {}
# startupProbe:
#   httpGet:
#     path: /health
#     port: http
#   initialDelaySeconds: 30
#   periodSeconds: 5
#   failureThreshold: 20

resources: {}

copyAppData:
  resources: {}

managedCertificate:
  enabled: false
  name: "mydomain-chat-cert"  # You can override this name if needed
  domains:
    - chat.example.com # update to your real domain

ingress:
  enabled: false
  class: ""
  # -- Use appropriate annotations for your Ingress controller, e.g., for NGINX:  
  annotations: {}
  #   # Example for GKE Ingress
  #   kubernetes.io/ingress.class: "gce"
  #   kubernetes.io/ingress.global-static-ip-name: "open-webui-external-ip"   #  you need to create this address in GCP console
  #   # Force HTTP to redirect to HTTPS
  #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  #   nginx.ingress.kubernetes.io/permanent-redirect: "https://chat.example.com"
  #   networking.gke.io/managed-certificates: "mydomain-chat-cert"
  #   # nginx.ingress.kubernetes.io/rewrite-target: / 
  host: "chat.example.com"  # update to your real domain 
  additionalHosts: []
  tls: false
  existingSecret: ""
persistence:
  enabled: true
  size: 2Gi
  # -- Use existingClaim if you want to re-use an existing Open WebUI PVC instead of creating a new one
  existingClaim: "pvc-ollama-web-gui"
  # -- Subdirectory of Open WebUI PVC to mount. Useful if root directory is not empty.
  subPath: ""
  # -- If using multiple replicas, you must update accessModes to ReadWriteMany
  accessModes:
    - ReadWriteMany
  storageClass: ""
  selector: {}
  annotations: {}

# -- Node labels for pod assignment.
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

# -- Affinity for pod assignment
affinity: {}

# -- Topology Spread Constraints for pod assignment
topologySpreadConstraints: []

# -- HostAliases to be added to hosts-file of each container
hostAliases: []

# -- Service values to expose Open WebUI pods to cluster
service:
  type: ClusterIP
  annotations: {}
  port: 80
  containerPort: 8080
  nodePort: ""
  labels: {}
  loadBalancerClass: ""

# Enables the use of OpenAI APIs
enableOpenaiApi: true

# -- OpenAI base API URL to use. Defaults to the Pipelines service endpoint when Pipelines are enabled, and "https://api.openai.com/v1" if Pipelines are not enabled and this value is blank
openaiBaseApiUrl: "https://api.openai.com/v1"

# -- OpenAI base API URLs to use. Overwrites the value in openaiBaseApiUrl if set
openaiBaseApiUrls: []
  # - "https://api.openai.com/v1"
  # - "https://api.company.openai.com/v1"

# -- Env vars added to the Open WebUI deployment. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration/
extraEnvVars:
  # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
  - name: OPENAI_API_KEY
    value: "0p3n-w3bu!"
  - name: OLLAMA_BASE_URL
    value: "ollama-service.ollama.svc.cluster.local:11434"
  - name: DATABASE_URL
    value: "postgresql://admin:password123@postgresql.common.svc.cluster.local:5432/ollama"
  # valueFrom:
  #   secretKeyRef:
  #     name: pipelines-api-key
  #     key: api-key
  # - name: OPENAI_API_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: openai-api-key
  #       key: api-key
  # - name: OLLAMA_DEBUG
  #   value: "1"

# -- Configure container volume mounts
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/>
volumeMounts:
  initContainer: []
  # - name: ""
  #   mountPath: ""
  container: []
  # - name: ""
  #   mountPath: ""

# -- Configure pod volumes
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/>
volumes: []
# - name: ""
#   configMap:
#     name: ""
# - name: ""
#   emptyDir: {}

# -- Configure pod security context
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-containe>
podSecurityContext:
  {}
  # fsGroupChangePolicy: Always
  # sysctls: []
  # supplementalGroups: []
  # fsGroup: 1001


# -- Configure container security context
# ref: <https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-containe>
containerSecurityContext:
  {}
  # runAsUser: 1001
  # runAsGroup: 1001
  # runAsNonRoot: true
  # privileged: false
  # allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: false
  # capabilities:
  #   drop:
  #     - ALL
  # seccompProfile:
  #   type: "RuntimeDefault"

# -- Extra resources to deploy with Open WebUI
extraResources:
  []
  # - apiVersion: v1
  #   kind: ConfigMap
  #   metadata:
  #     name: example-configmap
  #   data:
  #     example-key: example-value
```

I am using an external ollama instance in the same "ollama" namespace.

Do you see anything wrong with the configuration?

**Comment by 0xThresh** [comment]
Hi @kaliavarun, does your pod have outbound internet access? It seems like it might be stuck trying to download models. You might try enabling debug logging on the deployment to see if you get any other information.

**Comment by kaliavarun** [comment]
@0xThresh  Internet doesn't seem to be an issue.

```
root@open-webui-0:/app/backend# curl https://blackscreen.app/
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Black Screen</title>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <meta name='description' content='Just a black web page'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
  <link rel='canonical' href='https://blackscreen.app/'>
  <link rel="manifest" href="manifest.webmanifest">
  <link rel="stylesheet" href="style.css">
  <meta name='mobile-web-app-capable' content='yes'>
  <meta name='apple-mobile-web-app-capable' content='yes'>
  <meta name='application-name' content='Black screen'>
  <meta name='apple-mobile-web-app-status-bar-style' content='black'>
  <meta name='apple-mobile-web-app-title' content='Black screen'>
  <link rel='icon' sizes='192x192' href='/images/icon-192x192.png'>
  <link rel='apple-touch-icon' href='/images/icon-192x192.png'>
  <meta name='msapplication-TileImage' content='/images/icon-144x144.png'>
  <meta name='msapplication-TileColor' content='#000000'>
  <meta name='theme-color' content='#000000'>
  <meta property='og:title' content='Black screen'>
  <meta property='og:type' content='website'>
  <meta property='og:image' content='https://blackscreen.app/images/icon-192x192.png'>
  <meta property='og:url' content='https://blackscreen.app'>
  <meta property='og:description' content='Just a black web page'>
  <meta name='twitter:card' content='summary'>
  <meta name='twitter:url' content='https://blackscreen.app'>
  <meta name='twitter:title' content='Black screen'>
  <meta name='twitter:description' content='Just a black web page'>
  <meta name='twitter:image' content='https://blackscreen.app/images/icon-192x192.png'>
  <meta name='twitter:creator' content='@pyxeldev'>
</head>
<body>
  <div class="modal" id="modal-info">
    <div class="modal-bg modal-exit"></div>
    <div class="modal-container">
      <h1>Black Screen</h1>
      <h2>Just a black web page</h2>
      <p>Created by <a href="https://kevinpy.com" target="_blank">Kevin Py</a> for <a href="https://pyxel.dev" target="_blank">Pyxel</a>.</p>
      <p>Find the repository on <a href="https://gitlab.com/pyxeldev/blackscreen" target="_blank">Gitlab</a>.</p>
      <p>You can double-click anywhere on the page to cover your entire screen with black!</p>
      <p><a href="https://youtu.be/8H7mnObTScg" target="_blank">A 10 hours black screen video</a></p>
      <button class="modal-close modal-exit" autofocus>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" clas
s="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
      </button>
    </div>
  </div>
  <div class="info" data-modal="modal-info">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#888" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="fe
ather feather-info feather-info-hover"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="16" x2="12" y2="12"></line><line x1="12" y1="8" x2="12.01" y2="8"></line></svg>
  </div>
  <script src="./modal.js" async defer></script>
  <script src="./fullscreen.js" async defer></script>
</body>
</html>
root@open-webui-0:/app/backend#
```


I'm not sure how can I enable debug logs for this pod. I couldn't find relevant. options. I tried this

```
extraEnvVars:
  # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
  - name: OPENAI_API_KEY
    value: "0p3n-w3bu!"
  - name: OLLAMA_BASE_URL
    value: "ollama-service.ollama.svc.cluster.local:11434"
  - name: DATABASE_URL
    value: "postgresql://admin:password123@postgresql.common.svc.cluster.local:5432/ollama"
  - name: DEBUG
    value: "true"
  - name: LOG_LEVEL
    value: "debug"
```

**Comment by kaliavarun** [comment]
I was able to fetch the logs from the crashed container:

```
Loading...
  File "/app/backend/open_webui/routers/images.py", line 16, in <module>
    from open_webui.routers.files import upload_file
  File "/app/backend/open_webui/routers/files.py", line 18, in <module>
    from open_webui.routers.retrieval import ProcessFileForm, process_file
  File "/app/backend/open_webui/routers/retrieval.py", line 37, in <module>
    from open_webui.retrieval.vector.connector import VECTOR_DB_CLIENT
  File "/app/backend/open_webui/retrieval/vector/connector.py", line 26, in <module>
    VECTOR_DB_CLIENT = ChromaClient()
                       ^^^^^^^^^^^^^^
  File "/app/backend/open_webui/retrieval/vector/dbs/chroma.py", line 50, in __init__
    self.client = chromadb.PersistentClient(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/__init__.py", line 152, in PersistentClient
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/client.py", line 58, in __init__
    super().__init__(settings=settings)
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/shared_system_client.py", line 19, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/shared_system_client.py", line 32, in _create_system_if_not_exists
    new_system.start()
  File "/usr/local/lib/python3.11/site-packages/chromadb/config.py", line 444, in start
    component.start()
  File "/usr/local/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 150, in wrapper
    return f(*args, **kwargs)

```

I am wondering why it still used SQL lite, when I am using postgresql.

**Comment by kaliavarun** [comment]
I finally found the solution. In my case I am mounting a samba share as a PV and chromadb was sending byte range lock requests to the database in this share.


```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ollama-web-gui
  namespace: ollama
  labels:
    volume-id: pv-ollama-web-gui
spec:
  capacity:
    storage: 20Gi
  storageClassName: smb-storage-class
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  csi:
    driver: smb.csi.k8s.io
    volumeAttributes:
      source: "//192.168.0.100/ollama-web-gui"
    volumeHandle: pv-ollama-web-gui
  mountOptions:
    - guest
    - mfsymlinks
    - dir_mode=0775
    - file_mode=0775
    - **nobrl** 
    - cache=none
    - vers=3.0

```
I had to add `nobrl `mount option which prevents the client from sending byte range lock requests to the server.
