### ISSUE TITLE
`clusterDomain` Setting in Redis Sub-Chart Not Respected

### ISSUE THREAD

**Issue by mrclrchtr** [open-webui/helm-charts#210]
The clusterDomain setting in the Helm chart is not correctly applied to the Redis sub-chart. When specifying a custom cluster domain, such as:

```yaml
clusterDomain: cluster.test.local
redis-cluster:
  enabled: true
```

The expected domain should be used for the Redis service discovery. However, the resulting configuration still defaults to cluster.local, as seen in the generated environment variable:

```yaml
- name: REDIS_MASTER_HOST
  value: open-webui-redis-master-0.open-webui-redis-headless.open-webui.svc.cluster.local
```

Workaround:

```yaml
clusterDomain: cluster.test.local
redis-cluster:
  enabled: true
  clusterDomain: cluster.test.local
```
