### ISSUE TITLE
Disabling websocket in values yaml does not actually disable it

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [open-webui/helm-charts#215]
we were trying to set in the values.yaml for version 5.20.0

```
websocket:
   enabled: false
```

But this does not actually disable websockets
I needed to actually set this in the 
```
  extraEnvVars:
    # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
    - name: OPENAI_API_KEY
      value: "0p3n-w3bu!"
    - name: ENABLE_WEBSOCKET_SUPPORT
      value: "False"
```

I would have expected enabled: false to properly disable it, but it does not and there are lots of websocket errors
