### ISSUE TITLE
Pipelines persistency

### ISSUE THREAD

**Issue by jkleinkauff** [open-webui/helm-charts#239]
Hey friends!
This is not a bug I think. 

I've deployed OWUI and the pipelines module using this helm chart. To upload new pipelines to the platform, I have an initContainer in pipelines.extraInitContainer. The yaml also has the volume configuration to mount it to the pipelines folder properly.

```
  extraInitContainers:
    - name: fetch-github-folder
      image: appropriate/curl
      command:
        - sh
        - -c
        - |
          set -e
          echo "Fetching files from GitHub branch..."
          we clone the gh dir here.

```

This setup works ok. The problem is that whenever the pipeline pod is rebooted, any changes we've made to the Pipeline Valves are being overwritten by the default values configured in the pipe script. I understand why this is happening, since every time the pod boots it will clone the repo again. My question is if there is a better way of cloning the github repo or perhaps something to persist the pipeline changes?

Chart version: 6.0.0

Thank you!.
