### ISSUE TITLE
pgvector as vector database

### ISSUE THREAD

**Issue by terchris** [open-webui/helm-charts#249]
How to set up pgvector as vector database?

I have the following docker compose that uses pgvector. How to use pgvector as database like this `image: pgvector/pgvector:pg15` in the helm chart?

```yaml
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      - DATABASE_URL=postgresql://openwebui:openwebui@db:5432/openwebui
      - VECTOR_DB=pgvector
      - PGVECTOR_DB_URL=postgresql://openwebui:openwebui@db:5432/openwebui
      
      # Ollama Configuration - pointing to native Mac installation using rancher desktop
      - OLLAMA_BASE_URL=http://host.lima.internal:11434
      
      # RAG Configuration
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - RAG_EMBEDDING_ENGINE=ollama
      - RAG_EMBEDDING_MODEL=${RAG_EMBEDDING_MODEL:-nomic-embed-text:latest}

      # Tika Document Extraction
      - TIKA_SERVER_URL=http://tika:9998

      # Security
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      
      # Admin Configuration
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      
      # OIDC Configuration for Okta Red Cross
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME}
      - OPENID_PROVIDER_URL=${OPENID_PROVIDER_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OPENID_REDIRECT_URI=${OPENID_REDIRECT_URI}
      - OAUTH_SCOPES=openid email profile
      
      # OpenAI Configuration (if needed)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      

      
    volumes:
      - openwebui-data:/app/backend/data
    depends_on:
      - db
      - tika
    restart: unless-stopped
    networks:
      - openwebui-network

  db:
    image: pgvector/pgvector:pg15
    container_name: openwebui-db
    environment:
      - POSTGRES_USER=openwebui
      - POSTGRES_PASSWORD=openwebui
      - POSTGRES_DB=openwebui
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - openwebui-network

  tika:
    image: apache/tika:latest-full
    container_name: tika
    restart: unless-stopped
    ports:
      - "9998:9998"
    networks:
      - openwebui-network

volumes:
  openwebui-data:
  db-data:
  pgadmin-data:

networks:
  openwebui-network:
    driver: bridge

```
