### ISSUE TITLE
[question/request] CloudNative Postgres (CNPG) Support?

### ISSUE THREAD

**Issue by chr0n1x** [open-webui/helm-charts#257]
Hello,

I see in [the workload manager](https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/templates/workload-manager.yaml#L240-L243) that there's an option to inject a postgres DB URL.

I personally use CNPG to manage application databases: https://github.com/cloudnative-pg/charts

This chart/operator spins up a DB/cluster, pvc, replicas, etc _AND_ has init container/configs that allow me to auto-generate user accounts + passwords, writing those secrets to a namespace.

I'm wondering -- are there any plans on supporting k8s secrets in the db config for this chart? I'm not too familiar with the open-webui container env-vars and am wondering if instead of using `DATABASE_URL` if it is, or would eventually be, possible to do something like this instead:

```yaml
# somewhere in workload-manager.yaml
spec:
    template:
        metadata:
            spec:
            # ...
            containers:
            # ...
            - name: {{ .Chart.Name }}
              # ...
              env:
                - name: DATABASE_USER
                   valueFrom:
                     secretKeyRef:
                       name: {{ .Values.postgres.auth.secret.name }}
                       key: {{ .Values.postgres.auth.secret.userKey }}
                - name: DATABASE_PASSWORD
                     secretKeyRef:
                       name: {{ .Values.postgres.auth.secret.name }}
                       key: {{ .Values.postgres.auth.secret.passwordKey }}
                - name: DATABASE_URL
                   value: my-cnpg-db-cluster-svc.openwebui.svc.cluster.local
                - name: DATABASE_PORT
                   value: 5432
```
