### ISSUE TITLE
Pipelines Not Detected

### ISSUE THREAD

**Issue by Altair-Bueno** [open-webui/helm-charts#33]
### Expected behavior

Deploying the chart with the following values should enable pipelines

```yml
ollama:
  runtimeClassName: nvidia
  persistentVolume:
    enabled: true
  ollama:
    gpu:
      enabled: true
      type: nvidia
      number: 2
```

### Current behavior

Pipelines tab shows the message `Pipelines Not Detected`

![image](https://github.com/open-webui/helm-charts/assets/67512202/73218b7c-c5cd-4afc-9763-6478ab84505b)

### Current workaround

Setting the API key to `0p3n-w3bu!`, as noted by [pipelines' README](https://github.com/open-webui/pipelines), fixes this issue
