### ISSUE TITLE
Some settings like model whitelisting, default model and default user role are not persisted

### ISSUE THREAD

**Issue by oboudry-mvp** [open-webui/helm-charts#90]
On Open-WebUI deployed using the provided helm chart found at https://helm.openwebui.com/. With an existing persistent volume defined in `values.yaml` file and mounted as `/app/backend/data`. Users, custom prompts, are persistent across reboot. All works fine on that side.

But other settings like: 

- Default user role
- Default model
- Models whitelisting

are reset each time a new pod is created.

I did not find corresponding variables in the helm chart to define these values. Is there a way these can be persisted ?

**Comment by oboudry-mvp** [comment]
Sorry, should have digged a bit more before posting. I found the config.py file and noticed a lot of the config comes from environment variables. Setting these in my values file fixed the question.

```
extraEnvVars:
  # -- Default API key value for Pipelines. Should be updated in a production deployment, or be changed to the required API key if not using Pipelines
  - name: OPENAI_API_KEYS
    valueFrom:
      secretKeyRef:
        name: openai-config
        key: api-keys
  - name: OPENAI_API_BASE_URLS
    valueFrom:
      secretKeyRef:
        name: openai-config
        key: api-urls
  - name: ENABLE_MODEL_FILTER
    value: "true"
  - name: MODEL_FILTER_LIST
    value: "gpt-4o-mini;gpt-4o-2024-08-06;ask_hr_policies"
  - name: DEFAULT_MODELS
    value: "gpt-4o-mini"
  - name: DEFAULT_LOCALE
    value: "fr_FR"
  - name: DEFAULT_USER_ROLE
    value: "user"
  - name: MICROSOFT_CLIENT_ID
    value: "39f9d7b7-4595-468a-b088-8d86db174b33"
  - name: MICROSOFT_CLIENT_TENANT_ID
    value: "eb0565ca-9b1f-4a27-a2df-0dcbdeac9fa0"
  - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
    value: "true"
  - name: ENABLE_OAUTH_SIGNUP
    value: "true"
  - name: MICROSOFT_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: openai-config
        key: ms-client-secret

```
